### ISSUE TITLE
angel doesn't work in Chrome Version 39.0.2171.95 (64-bit)

### ISSUE THREAD

**Issue by tjyang** [riscv-software-src/riscv-angel#12]
Hi Sagar

Following is the screenshot running angel in Chrome broswer, it works in FireFox.

![image](https://cloud.githubusercontent.com/assets/378638/5577279/78abd9d6-8fd3-11e4-93e7-45b392abca45.png)

**Comment by sbeamer** [comment]
scroll up

**Comment by tjyang** [comment]
indeed, "scroll up" fix the issue. Sorry for the disturbance.
