### ISSUE TITLE
Local instance of angel doesn't seem to work

### ISSUE THREAD

**Issue by The-Blue-Wizard** [riscv-software-src/riscv-angel#16]
Riscv-angel works on Firefox when launched straight from the Internet. But, after git-cloning riscv-angel and then using python -m SimpleHTTPServer and entering http://127.0.0.1:8000/run.html in Firefox, I got the familiar emulator webpage, complete with a dialog with "Close and launch" button. I clicked on it, and nothing happens. Why is it apparently broken versus straight-from-Internet launching? I see there is vmlinux in lib/riscv_compiled. I find the HTML and Javascript codes difficult to decipher. Thanks for any help.

**Comment by sagark** [comment]
You probably need to run `make` in the riscv-angel directory to generate inst.js

**Comment by The-Blue-Wizard** [comment]
It's now working! Thanks! Issue now closed.
