### ISSUE TITLE
Write or Find/Hook-in a better js terminal emulator

### ISSUE THREAD

**Issue by sagark** [riscv-software-src/riscv-angel#6]

**Comment by a0u** [comment]
There is [termlib.js](http://www.masswerk.at/termlib/), although ANSI support is currently limited to SGR.  If you plan to write your own, may I suggest implementing some pragmatic subset of [`console_codes(4)`](http://man7.org/linux/man-pages/man4/console_codes.4.html) such that at least ncurses works?

Filtering out all escape sequences could be an interim solution.  After all, who needs vi when there is ed?
- [X3.64 escape sequences by mnemonic](http://paulbourke.net/dataformats/ascii/)
- [VT100 programming manual](http://vt100.net/docs/vt100-ug/chapter3.html)

**Comment by sagark** [comment]
Done, used: https://github.com/chjj/term.js/
